# Generated by Django 4.2.2 on 2023-07-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_contact_delete_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="Email",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="contact",
            name="Name",
            field=models.CharField(max_length=70),
        ),
    ]
