# Generated by Django 4.2.2 on 2023-07-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_contact_email_alter_contact_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="blog",
            fields=[
                ("SIno", models.AutoField(primary_key=True, serialize=False)),
                ("Author", models.CharField(max_length=20)),
                ("Email", models.CharField(max_length=30)),
                ("Title", models.CharField(max_length=30)),
                ("Content", models.TextField()),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
