# Generated by Django 4.2.2 on 2023-07-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_rename_blog_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.CharField(default="er", max_length=30),
            preserve_default=False,
        ),
    ]
