# Generated by Django 4.2.2 on 2023-07-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_rename_usern_postcomments_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="Author",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="post",
            name="Title",
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(max_length=150),
        ),
    ]
